mongodb:
#  uri: "mongodb://127.0.0.1:27018,127.0.0.1:27019,127.0.0.1:27020/?replicaSet=myReplicaSet"
  uri: "mongodb://localhost:27017"
  database: "env_db"
  staticDemColl: "col_test"
  dynamicColl: "col_test"
  craterColl: "craters"

rabbitmq:
  url: "amqp://guest:guest@localhost:5672"